nan-sso-ggong/store-management-system

- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/Headquarters.java
- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/ItemHQ.java
- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/Order.java
- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/OrderApplication.java
- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/type/ItemCategory.java
본사, 본사 상품, 발주신청 엔티티를 추가하였습니다. 아직 공급처 테이블이 만들어지지 않아서 공급 신청은 후에 추가하도록 하겠습니다.
> ✨ [FEAT] 본사 엔티티 추가

- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/ItemHQ.java
- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/Store.java
- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/WarehousingApplication.java
- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/type/ItemCategory.java
- cs25backend/src/main/java/edu/dongguk/cs25backend/domain/type/UserRole.java
> ✨ [FEAT] 본사 발주 신청 엔티티 추가 및 enum 수정

- .idea/vcs.xml
- .idea/workspace.xml
- Frontend/customer/src/App.css
- Frontend/customer/src/App.js
- Frontend/customer/src/Axios.js
- Frontend/customer/src/Components/Sidebar.jsx
- Frontend/customer/src/Components/Topbar.jsx
- Frontend/customer/src/Pages/SelectStore.jsx
- Frontend/customer/src/index.css
> ✨ 점포 선택 페이지 구현

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ExceptionController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/StoreController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemCS.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Manager.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Order.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderItemCS.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/OrderStatus.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ManagerRequestDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/StoreRequestDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ManagerRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ManagerService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
점주, 점포, 주문 엔티티 추가 및  점주 점포 추가 기능 구현
> ✨ 점주, 점포, 주문 엔티티 추가 및  점주 점포 추가 기능 구현

- .idea/workspace.xml
- Frontend/customer/src/Components/Sidebar.jsx
- Frontend/customer/src/Components/Topbar.jsx
- Frontend/customer/src/Pages/SelectItems.jsx
- Frontend/customer/src/Pages/SelectStore.jsx
- Frontend/customer/src/index.css
> ✨ 상품 선택 페이지

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/WarehousingApplication.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ItemCategory.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ItemHQRequestDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/StockResponseDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/HeadquartersRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemHQRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
보유 재고 목록 조회 API를 구현했고 상품 추가는 오늘 하루 안에 끝날 것 같습니다!
다만 보유 재고 목록 조회에서 입고일을 어떻게 처리할지는 아직 생각중입니다.
- 보유 재고 목록 조회 API 구현
- 상품 추가 구현중
> ✨ [FEAT] 본사 보유 재고 목록 조회 완료

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Image.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/Extension.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ImageCategory.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ImageRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/util/FileUtil.kt
본사 상품 추가 API와 이에 필요한 이미지 Entity를 만들었고 이미지 업로드에 필요한 FileUtil 클래스를 만들었습니다.
- 본사 상품 추가 API 구현
- 이미지 Entity 추가
- 이미지 업로드 util 클래스 구현
다만 아직 이미지를 삭제하는 로직을 구현하지는 않았기 때문에 이미지 수정 시 이전 이미지를 삭제하는 로직은 추후에 구현하도록 하겠습니다.
> ✨ [FEAT] 본사 상품 추가 API 구현 및 이미지 업로드 기능 구현

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Headquarters.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Image.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/WarehousingApplication.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ItemCategory.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/Supplier.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ItemHQUpdateDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/ItemDetailResponseDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/StockResponseDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/AuthService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/util/FileUtil.kt
본사 재고 관리쪽 API 구현이 끝났습니다. 자주 이용되는 이미지 업로드 기능의 경우 아예 FileUtil 클래스에 toEntity 메서드로 분리해놨으니 사용하시면 됩니다.
- 보유 재고 상세 조회 구현
- 상품 수정 구현
- 상품 삭제 구현
- FileUtil 클래스 수정
- ItemCategory, Supplier JsonCreater 구현
> ✨ [FEAT] 본사 재고 관리 API 구현

- .idea/workspace.xml
- Frontend/customer/src/Components/Sidebar.jsx
- Frontend/customer/src/Components/Topbar.jsx
- Frontend/customer/src/Pages/SelectItems.jsx
- Frontend/customer/src/Pages/SelectStore.jsx
- Frontend/customer/src/state.js
StoreId, StoreName, UserName을 Recoil을 통한 전역 상태 관리
> ⚡ Recoil을 통한 전역상태관리

- .idea/workspace.xml
- Frontend/customer/src/Components/Sidebar.jsx
- Frontend/customer/src/Components/Topbar.jsx
- Frontend/customer/src/Pages/SelectItems.jsx
- Frontend/customer/src/state.js
새로고침시 점포Id, 점포명이 초기화되는 오류등 상태관리 문제 수정
> 🐛 새로고침시 점포Id, 점포명이 초기화되는 오류 수정

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ManagerService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
- 점포 목록 조회
- 점포 정보 편집
에 관련된 API 로직 및 Service 위치 수정을 했습니다.
> 🐛  [FIX] 점포 관련 API Service 위치 이동 및 로직 수정

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ItemCategory.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ReleaseStatus.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/Supplier.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/OrderResponseDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemHQRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderApplicationRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemCSService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderApplicationService.kt
본사 입고 관리 발주 목록 조회 API를 구현했고 enum에서 문자열에 맞는 enum을 가지고오는 get'Enum클래스'에서 null값 반환을 허용하도록 했습니다. null값 반환시 이를 category is null과 같은 쿼리문을 써서 모든 카테고리를 반환할 수 있도록 쿼리를 만들면 될 것 같습니다!
- 본사 입고 관리 발주 목록 조회 API 구현
- enum 반환 수정
> ✨ [FEAT] 본사 입고 관리 발주 목록 조회 API 구현 및 enum 반환 수정

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Manager.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ApplyRequestDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ManagerRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ManagerService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
> ✨ 점주 및 점포 신청 승인 거절

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/StoreController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/StoreRequestDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/HeadquartersRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ManagerRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/AuthService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
> ✨ 점포 신청 구현/점주, 본사 회원가입 중복 처리

- .idea/workspace.xml
- Frontend/customer/package.json
- Frontend/customer/src/Pages/SelectItems.jsx
- Frontend/customer/src/Pages/SelectStore.jsx
- Frontend/customer/src/Pages/ShoppingCart.jsx
- Frontend/customer/src/state.js
- Frontend/customer/yarn.lock
> ✨ 장바구니 로직 구현, UI 일부 구현

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/CustomerController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ExceptionController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemCS.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/CustomerItemSearch.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/ItemsResponse.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemCSRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemCSService.kt
> 🎨 소비자 상품 목록 조회

- .idea/workspace.xml
- Frontend/customer/src/Pages/CheckPayment.jsx
- Frontend/customer/src/Pages/ShoppingCart.jsx
axios 연동 체크 및 구현, api 수정에 따른 일부 변경
> 🚑 장바구니 api수정에 따른 변경

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ReleaseRequestDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/WarehousingRequestDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/WarehousingRequestDtos.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/ReleaseStockResponseDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderApplicationRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderApplicationService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/WarehousingApplicationService.kt
출고 관리 API 구현 완료했습니다.
- 출고 관리 발주 목록 조회
- 출고 신청 발주 목록 조회
- 출고 신청 발주 목록 신청
> feat: 출고 관리 API 구현

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/OrderItemResponseDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/PickupOrderRequestDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemCSRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderApplicationRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderCSService.kt
점주가 발주 관리를 하기 위한 API를 구현했습니다.
- 발주 목록 조회
- 발주 신청
> ✨ [FEAT] 점주 - 발주 관리 관련 API 관련

- .idea/workspace.xml
- Frontend/customer/src/Pages/CheckPayment.jsx
- Frontend/customer/src/Pages/ShoppingCart.jsx
결제 직후 결제 정보 조회 페이지 구현했습니다.
Postman을 활용하여 axios 통신 또한 체크 완료했습니다.
> ✨ 결제 직후 결제 정보 조회 페이지 구현

- .idea/workspace.xml
- Frontend/customer/src/Pages/PaymentList.jsx
- Frontend/customer/src/Pages/ShoppingCart.jsx
구매 내역 조회 페이지 구현했습니다.
Postman을 이용해서 데이터를 정상적으로 받아오는지 확인했습니다.
> ✨ 구매 내역 조회 페이지 구현

- .idea/workspace.xml
- Frontend/customer/src/Components/Topbar.jsx
- Frontend/customer/src/Pages/PaymentListDetail.jsx
구매 내역 상세 로직 구현했습니다.
Postman으로 axios 통신 확인했습니다.
> ✨ 구매 내역 상세 로직 구현

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/WarehousingApplication.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemHQRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/WarehousingApplicationService.kt
아래 사항들의 버그를 수정했습니다.
- 상품 수정시 이미지를 보내지 않을 시 수정되지 않는 버그 수정
- 출고 관리 재고 조회 시 상품 상태 버그 수정
> 🐛 [FIX] 본사 API 버그 수정

- .idea/workspace.xml
- Frontend/customer/src/Pages/PaymentList.jsx
- Frontend/customer/src/Pages/PaymentListDetail.jsx
> 💄  구매 내역 조회 페이지 완료

- .idea/workspace.xml
- Frontend/customer/src/App.js
- Frontend/customer/src/Axios.js
- Frontend/customer/src/Pages/Login/GoogleAfterLogin.jsx
- Frontend/customer/src/Pages/Login/GoogleLogin.jsx
- Frontend/customer/src/Pages/Login/KakaoAfterLogin.jsx
- Frontend/customer/src/Pages/Login/KakaoLogin.jsx
- Frontend/customer/src/Pages/Login/NaverAfterLogin.jsx
- Frontend/customer/src/Pages/Login/NaverLogin.jsx
- Frontend/customer/src/index.js
> 🐛 로그인 로직 수정

- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/StoreDetailResponseDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
-  점포 목록의 ResponseBody에 점포 이미지 추가
-  점포 목록을 보낼때 승인된 점포만 반환
> 🐛 [FIX] 점주 - 점포 목록 조회 API 수정

- .idea/workspace.xml
- Frontend/customer/src/Axios.js
- Frontend/customer/src/Pages/Login/GoogleAfterLogin.jsx
- Frontend/customer/src/Pages/Login/KakaoAfterLogin.jsx
- Frontend/customer/src/Pages/Login/NaverAfterLogin.jsx
- Frontend/customer/src/Pages/SelectStore.jsx
로그아웃 후 다시 로그인시  localStorage의 access_token 값이 변경되더라도, 이미 생성된 api 인스턴스의 Authorization 헤더 값은 변경되지 않아 발생하는 문제 해결
> 🐛 로그아웃 후 다시 로그인시 발생하는 문제 해결

- .idea/workspace.xml
- Frontend/customer/src/Axios.js
- Frontend/customer/src/Pages/Login/GoogleAfterLogin.jsx
- Frontend/customer/src/Pages/Login/KakaoAfterLogin.jsx
- Frontend/customer/src/Pages/Login/NaverAfterLogin.jsx
기존의 방식에서 매 요청 시마다 Authorization 헤더를 설정하는 방식으로 수정하였습니다
> 🐛 로그아웃 후 다시 로그인 할 때 생기는 버그 수정

- cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/JoinRequestForManager.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
> 🐛 점포 생성자 오류 수정

- .idea/workspace.xml
- Frontend/customer/src/Pages/PaymentList.jsx
- Frontend/customer/src/Pages/ShoppingCart.jsx
장바구니에서 구매할 때, 잔액이 부족할 경우 예외처리 구현
주문 내역 리스트에서 주문상태에 따른 다른 색으로 구별 가능하도록 구현
> ✨ 잔액부족시 예외처리, 주문내역내 주문상태 색으로 구별 구현

- .idea/workspace.xml
- Frontend/customer/src/Pages/SelectItems.jsx
- Frontend/customer/src/Pages/SelectStore.jsx
물품 선택 시 장바구니에 존재하는 해당 상품 개수 확인 기능 구현했습니다
> ✨ 물품 선택 시 장바구니에 존재하는 해당 상품 개수 확인 기능 구현

- cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/StoreController.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/OrderApplicationListDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderApplicationRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderApplicationService.kt
> ✨  발주 목록 불러오기 구현

- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/OrderApplicationListDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderApplicationRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemCSService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderApplicationService.kt
> ⚡  발주 목록 상품 id도 가져오도록 수정

- cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemHQRepository.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
중복 상품 예외 처리를 추가하였습니다.
- 상품 추가, 수정 시 중복 상품 예외 처리 추가
> ✨ [FEAT] 중복 상품 예외 처리 추가

- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/OrderApplicationListDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/OrderItemResponseDto.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderApplicationService.kt
- cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderCSService.kt
> ⚡ 카테고리 한글 변경

- .idea/workspace.xml
- Frontend/store/src/Pages/PaymentList.jsx
> ✨ 점주: 주문내역 관리 모든 기능 구현
